# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#272e33\033\\"
printf "\033]4;1;#e67e80\033\\"
printf "\033]4;2;#a7c080\033\\"
printf "\033]4;3;#dbbc7f\033\\"
printf "\033]4;4;#7fbbb3\033\\"
printf "\033]4;5;#d699b6\033\\"
printf "\033]4;6;#83c092\033\\"
printf "\033]4;7;#d3c6aa\033\\"
printf "\033]4;8;#475258\033\\"
printf "\033]4;9;#e67e80\033\\"
printf "\033]4;10;#a7c080\033\\"
printf "\033]4;11;#dbbc7f\033\\"
printf "\033]4;12;#7fbbb3\033\\"
printf "\033]4;13;#d699b6\033\\"
printf "\033]4;14;#83c092\033\\"
printf "\033]4;15;#d3c6aa\033\\"

# Background
printf "\033]11;#272e33\033\\";

# Foreground
printf "\033]10;#d3c6aa\033\\";

# Cursor
printf "\033]12;#d3c6aa\033\\";

# Border
printf "\033]7044;#d3c6aa\033\\";
