# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#111215\033\\"
printf "\033]4;1;#414867\033\\"
printf "\033]4;2;#60696e\033\\"
printf "\033]4;3;#6f777c\033\\"
printf "\033]4;4;#7d9f9b\033\\"
printf "\033]4;5;#89acad\033\\"
printf "\033]4;6;#9fc1a5\033\\"
printf "\033]4;7;#ffffff\033\\"
printf "\033]4;8;#4a5259\033\\"
printf "\033]4;9;#505980\033\\"
printf "\033]4;10;#778388\033\\"
printf "\033]4;11;#8b949b\033\\"
printf "\033]4;12;#9cc6c1\033\\"
printf "\033]4;13;#acd5d9\033\\"
printf "\033]4;14;#c6f1ce\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#111215\033\\";

# Foreground
printf "\033]10;#ffffff\033\\";

# Cursor
printf "\033]12;#ffffff\033\\";

# Border
printf "\033]7044;#ffffff\033\\";
