# Generated by hellwal

wallpaper='/home/cal/.config/hellwal/themes/everforest.hellwal'

background='272e33'
foreground='d3c6aa'
cursor='d3c6aa'
border='d3c6aa'

color0='272e33'
color1='e67e80'
color2='a7c080'
color3='dbbc7f'
color4='7fbbb3'
color5='d699b6'
color6='83c092'
color7='d3c6aa'
color8='475258'
color9='e67e80'
color10='a7c080'
color11='dbbc7f'
color12='7fbbb3'
color13='d699b6'
color14='83c092'
color15='d3c6aa'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
