#  ┏┓┏┳┓┏┓┳┓┏┓┓┏┳┏┓  ┳┓┳┳┳┓┳┓┓ ┏┓┏┓
#  ┗┓ ┃ ┣┫┣┫┗┓┣┫┃┃┃━━┣┫┃┃┣┫┣┫┃ ┣ ┗┓
#  ┗┛ ┻ ┛┗┛┗┗┛┛┗┻┣┛  ┻┛┗┛┻┛┻┛┗┛┗┛┗┛
#                                  


# Print a new line at the start of the prompt
add_newline = true

# Format of the status
format = """
$os $cmd_duration $directory $git_branch $git_status
$character
"""

#--------os-----------#
#---------------------#
[os]
style = 'bold bg:black fg:blue'
format = '[](bold fg:black)[$symbol]($style)[](bold fg:black)'
disabled = false

[os.symbols]
Arch = "󰣇 "
EndeavourOS = " "

#-------character--------#
#------------------------#
[character]
success_symbol = "[   ](bold fg:purple)"
error_symbol = "[   ](bold fg:red)"
vimcmd_symbol = "[   ](bold fg:yellow)"
vimcmd_visual_symbol = "[   ](bold fg:blue)"
vimcmd_replace_symbol = "[   ](bold fg:green)"
vimcmd_replace_one_symbol = "[   ](bold fg:green)"

#------directory---------#
#------------------------#
[directory]
style = 'bold bg:black fg:bright-white'
truncation_length = 6
truncation_symbol = "../"
format = '[](bold fg:black)[$path]($style)[](bold fg:black)'

#------gitBranch-------#
#----------------------#
[git_branch]
symbol = ""
truncation_length = 12
truncation_symbol = ""
format = '[](bold fg:black)[$symbol $branch(:$remote_branch)](bold fg:blue bg:black)[](bold fg:black)'

#------gitStatus-------#
#----------------------#
[git_status]
style = "bold purple"
format = "[$modified$deleted$untracked$ahead_behind]($style) "
modified = " "
deleted = " "
untracked = " "
ahead = " "
behind = " "
up_to_date = " "

#-----cmdDuration------#
#----------------------#
[cmd_duration]
min_time = 0
format = '[](bold fg:black)[󰪢 $duration](bold bg:black fg:red)[](bold fg:black)'
